# Generated by Django 5.0.4 on 2024-04-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hastalar',
            fields=[
                ('hastaID', models.IntegerField(primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('dogumTarihi', models.DateField()),
                ('cinsiyet', models.CharField(max_length=5)),
                ('telNo', models.CharField(max_length=10)),
                ('adres', models.CharField(max_length=50)),
            ],
        ),
    ]
