# Generated by Django 5.0.4 on 2024-04-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hastalar',
            name='dogumTarihi',
            field=models.CharField(max_length=50),
        ),
    ]
