# Generated by Django 5.0.4 on 2024-04-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_alter_hastalar_dogumtarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hastalar',
            name='hastaID',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
