# Generated by Django 5.0.4 on 2024-04-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_alter_hastalar_hastaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hastalar',
            name='hastaID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
