# Generated by Django 5.0.4 on 2024-04-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_alter_hastalar_hastaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doktorlar',
            fields=[
                ('doktorID', models.IntegerField(primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('uzmanlikAlani', models.CharField(max_length=50)),
                ('calistigiHastane', models.CharField(max_length=50)),
            ],
        ),
    ]
