# Generated by Django 5.0.4 on 2024-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0005_doktorlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raporlar',
            fields=[
                ('raporID', models.IntegerField(primary_key=True, serialize=False)),
                ('raporTarihi', models.CharField(max_length=50)),
                ('raporIcerigi', models.CharField(max_length=50)),
            ],
        ),
    ]
