# Generated by Django 5.0.4 on 2024-05-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0006_raporlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='raporlar',
            name='raporJSON',
            field=models.TextField(null=True),
        ),
    ]
