# Generated by Django 5.0.4 on 2024-05-06 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0007_raporlar_raporjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='raporlar',
            name='hastaID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminpage.hastalar'),
        ),
    ]
