# Generated by Django 5.0.4 on 2024-05-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0008_raporlar_hastaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raporlar',
            name='hastaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpage.hastalar'),
        ),
    ]
