# Generated by Django 5.0.4 on 2024-05-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0012_resimler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resimler',
        ),
    ]
