# Generated by Django 5.0.4 on 2024-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0013_delete_resimler'),
    ]

    operations = [
        migrations.AddField(
            model_name='raporlar',
            name='resimURL',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
