# Generated by Django 5.0.4 on 2024-05-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0014_raporlar_resimurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raporlar',
            name='resimURL',
            field=models.CharField(max_length=200),
        ),
    ]
