# Generated by Django 5.0.4 on 2024-05-08 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0015_alter_raporlar_resimurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='BildirimSistemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hastaID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpage.hastalar')),
                ('raporID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpage.raporlar')),
            ],
        ),
    ]
