# Generated by Django 5.0.4 on 2024-04-30 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpage', '0006_raporlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Randevular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randevuTarihi', models.CharField(max_length=10)),
                ('doktorID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpage.doktorlar')),
                ('hastaID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpage.hastalar')),
            ],
        ),
    ]
