# Generated by Django 5.0.4 on 2024-05-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_randevular_randevusaati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevular',
            name='randevuSaati',
            field=models.CharField(max_length=5),
        ),
    ]
